### ISSUE TITLE
Remove hard-coded goodnight-lead.herokuapp.com in session URL's

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#24]
Session URL's start with goodnight-lead.herokuapp.com when running on my computer. Presumably this behaviour is independent of the host. Ideally the session URL should have the name of the host where it's currently running.

To fix: You can get the current domain name from the HTTP request.

**Comment by EricHorton** [comment]
This is configured in admin.py. See the comment I left. Django has no officially supported way of getting a request object in the place we need it to be in order to build a url. There are hacks, of course, such as getting it elsewhere and storing it as self.request, but that is not necessarily a better fix. 

If you do find a better solution, feel free to implement it. 

Eric Horton

**Comment by srmagura** [comment]
Your environment variable solution is fine for development, but presumably that environment variable will not be set on leadlabdemo.herokuapp.com, right?

I have another solution in mind that I will probably implement eventually. Not an urgent issue.

**Comment by EricHorton** [comment]
Heroku fully supports setting any environment variables an needed for app configuration. 

Eric Horton
